version: '3'
services:
  postgres:
    container_name: postgres
    image: postgres:15-alpine
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=doggr
      - POSTGRES_PASSWORD=doggr
      - POSTGRES_DB=doggr
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U doggr" ]
      interval: 10s
      timeout: 5s
      retries: 25

  root_review:
    container_name: root_review
    build: ./root_review/
    restart: always
    ports:
      - "3333:3333"
    environment:
      - DATABASE_URL=postgres://tuber:tuber@postgres/tuber
    depends_on: #This is a lie
      - postgres

volumes:
  db:
    driver: local